### PR TITLE
CPT-697: accept mixed-language uploads

### PR DESCRIPTION
**Pull request by internetti**
most relevant changes are in internal/locales/i18n.go:
* LoadTranslations - loading all available locales into the localizer right on init, and picking the needed one on demand
* GetDBColumns - check in all available locales for a match, if none found, check original db fields. otherwise, throw error
* GetAvailableLocales - getting the language names right from the toml files, reducing redundancy
* Translate - get translation for currently set language
* TranslateFrom - get translation for language given as argument

file for testing: [generated_5_mixed.csv](https://github.com/NorwegianRefugeeCouncil/core/files/13751061/generated_5_mixed.csv)

### CODE REVIEW

**Review by dfigueroa87 — COMMENTED** [review]
I'm getting an error when trying to upload files locally.
I tried both with a file I had already download in previous version, and also with a file generated by downloading all the test participants I created (1 anonymous and 1 with only full name). In both cases this is the error:

image

And here's the file: 
[download (5).xlsx](https://github.com/NorwegianRefugeeCouncil/core/files/13829017/download.5.xlsx)

**Comment by dfigueroa87** [comment]
I think deduplication may got broken now.
I uploaded twice a file having just one participant with full name.
When I went to upload it a third time, I checked the full name deduplication checkbox, and the app crashed.

```
deploy-db-1            | 2024-01-05 10:05:17.105 UTC [61] ERROR:  invalid input syntax for type uuid: ""
deploy-db-1            | 2024-01-05 10:05:17.105 UTC [61] CONTEXT:  unnamed portal parameter $1 = '...'
deploy-db-1            | 2024-01-05 10:05:17.105 UTC [61] STATEMENT:  INSERT INTO temp_individuals_53879c47_d95a_4d0f_b260_5e610a055166 SELECT * FROM UNNEST($1::uuid[],$2::varchar[]);
```

**Comment by internetti** [comment]
> I think deduplication may got broken now. I uploaded twice a file having just one participant with full name. When I went to upload it a third time, I checked the full name deduplication checkbox, and the app crashed.
> 
> ```
> deploy-db-1            | 2024-01-05 10:05:17.105 UTC [61] ERROR:  invalid input syntax for type uuid: ""
> deploy-db-1            | 2024-01-05 10:05:17.105 UTC [61] CONTEXT:  unnamed portal parameter $1 = '...'
> deploy-db-1            | 2024-01-05 10:05:17.105 UTC [61] STATEMENT:  INSERT INTO temp_individuals_53879c47_d95a_4d0f_b260_5e610a055166 SELECT * FROM UNNEST($1::uuid[],$2::varchar[]);
> ```

I'm having trouble replicating that, can you describe this in more detail?

**Comment by dfigueroa87** [comment]
> I'm having trouble replicating that, can you describe this in more detail?

First I deleted all the participants in a `test` country.
Then uploaded this file: 
[download.xlsx](https://github.com/NorwegianRefugeeCouncil/core/files/13840905/download.xlsx)
Then uploaded the same file again, selecting deduplication based on full name

**Comment by internetti** [comment]
> > I'm having trouble replicating that, can you describe this in more detail?
> 
> First I deleted all the participants in a `test` country. Then uploaded this file: [download.xlsx](https://github.com/NorwegianRefugeeCouncil/core/files/13840905/download.xlsx) Then uploaded the same file again, selecting deduplication based on full name

I'm afraid this is not broken by this branch. this is broken on main. I'll create a new PR for the fix

**Review by dfigueroa87 — APPROVED** [review]

**Pull request merged**
