### PR TITLE
COR-600: fix single individual deletion

### PR DESCRIPTION
**Pull request by internetti**
deletion of single individuals didn't work, because the button was disabled before submitting the form

### CODE REVIEW

**Comment by ludydoo** [comment]
I tried deleting a single individual on main and it worked. Can you try with a clean install ?

**Comment by internetti** [comment]
what do you mean by clean install? make down etc? did that, doesn't work. also doesn't work on staging for me

**Comment by ludydoo** [comment]
@internetti that's very strange. Just tested it locally...

**Comment by ludydoo** [comment]
Let's check it out tomorrow

**Review by ludydoo — APPROVED** [review]

**Pull request merged**
