### PR TITLE
[CORE24-557] feat(households): Include individuals in household response

### PR DESCRIPTION
**Pull request by dfigueroa87**
Jira ticket: JIRA-CORE24-557

## What have you implemented?

- Overrided the `get` function in the household service so it calls the individuals service to retrieve the individuals in the household.
- Created a `RelationStore` interface to retrieve entities based on a 1-N relation. In this case the IndividualStore extends it so it can retrieve a list of individuals from a household. Note that this is a very basic implementation intended only for solving this first particular use case. We can continue to refine the abstraction while building new features. 
- Moved the query to retrieve individuals by their id so it can be used both for getting a single individual and also for getting all individuals in a household.

## How to test it?

Call GET /households/:id and expect the response to contain the populated `individuals` array.

### CODE REVIEW

**Review by internetti — COMMENTED** [review]
when opening an indiviual from the table, I get this:
```
Corrupt data in database for individuals: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "null",
    "path": [
      "languages"
    ],
    "message": "Expected array, received null"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "null",
    "path": [
      "emails"
    ],
    "message": "Expected array, received null"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "null",
    "path": [
      "phones"
    ],
    "message": "Expected array, received null"
  },
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "null",
    "path": [
      "identification"
    ],
    "message": "Expected array, received null"
  }
]
```

**Comment by dfigueroa87** [comment]
> when opening an indiviual from the table, I get this:
> 
> ```
> Corrupt data in database for individuals: [
>   {
>     "code": "invalid_type",
>     "expected": "array",
>     "received": "null",
>     "path": [
>       "languages"
>     ],
>     "message": "Expected array, received null"
>   },
>   {
>     "code": "invalid_type",
>     "expected": "array",
>     "received": "null",
>     "path": [
>       "emails"
>     ],
>     "message": "Expected array, received null"
>   },
>   {
>     "code": "invalid_type",
>     "expected": "array",
>     "received": "null",
>     "path": [
>       "phones"
>     ],
>     "message": "Expected array, received null"
>   },
>   {
>     "code": "invalid_type",
>     "expected": "array",
>     "received": "null",
>     "path": [
>       "identification"
>     ],
>     "message": "Expected array, received null"
>   }
> ]
> ```

Good catch! I fixed it by adding fallbacks in the query for the aggregations (before it was working because we were joining the data in code, moving it to the query broke it)

**Review by internetti — COMMENTED** [review]
:clown_face: I find the naming a bit confusing. it makes me wonder if this could just be a regular filter in the list method

**Comment by dfigueroa87** [comment]
> 🤡 I find the naming a bit confusing. it makes me wonder if this could just be a regular filter in the list method

Terrible name, I agree.
But there's also 2 main reasons I didn't use the existing `list` function:
- As a side effect, it would modify the endpoint to also allow filtering by householdId. (plus adding an extra table join)
- The return type from `list` is a subset of the individual fields meant for the table view in the individuals list page. For households we defined the type to be the full individual (even though all fields are not really needed)

**Comment by internetti** [comment]
> > 🤡 I find the naming a bit confusing. it makes me wonder if this could just be a regular filter in the list method
> 
> Terrible name, I agree. But there's also 2 main reasons I didn't use the existing `list` function:
> 
> * As a side effect, it would modify the endpoint to also allow filtering by householdId. (plus adding an extra table join)
> * The return type from `list` is a subset of the individual fields meant for the table view in the individuals list page. For households we defined the type to be the full individual (even though all fields are not really needed)

Maybe we could also think about getting rid of the list item type and just return the normal entities. since we already got rid of the household individual type.
but I'll approve this

**Comment by dfigueroa87** [comment]
> > > 🤡 I find the naming a bit confusing. it makes me wonder if this could just be a regular filter in the list method
> > 
> > 
> > Terrible name, I agree. But there's also 2 main reasons I didn't use the existing `list` function:
> > 
> > * As a side effect, it would modify the endpoint to also allow filtering by householdId. (plus adding an extra table join)
> > * The return type from `list` is a subset of the individual fields meant for the table view in the individuals list page. For households we defined the type to be the full individual (even though all fields are not really needed)
> 
> Maybe we could also think about getting rid of the list item type and just return the normal entities. since we already got rid of the household individual type. but I'll approve this

Yeah, that could simplify some things, and for individuals wouldn't be a problem as it's only few extra fields. But thinking ahead, for households I think it's going to be a bigger difference, since for the list items we only really need a few fields from the head of household.

I guess what could work is to find a common reduced set of fields between the list items and the individuals in the household, and use that in both places. But for now I'll merge this as is, and we can re-assess later.

**Pull request merged**
