### PR TITLE
COR-505 New Individual Form

### PR DESCRIPTION
**Pull request by ludydoo**
This PR is overall aimed at updating the Individual to match the product requirements. 
- Adds all the required fields to the `Individual` struct
- Creates the corresponding form with all the elements and sections.
- Adds validation on required fields, etc. for the individual
- Adds an ISO list of countries and languages for `<select>`
- Changes the ID types from `xid` to `uuid` (countries and individuals). Might as well do it now than later
- Adds the migration to create the DB table and fields
- Adds alerts on success/failure to create/update an individual
- Adds focusing on errored fields if the form had errors. Otherwise focuses on the first input. 
- Adds some non-input form fields, as the Individual form is massive. Needs some spacing between elements.
- Fix the generator to generate data that corresponds to the new form

### CODE REVIEW

**Comment by neb42** [comment]
COR-505 is a big ticket. Can you add a description outlining what parts of the ticket this covers and what's remaining. This should have been split into sub-tickets and smaller prs probably.

**Comment by neb42** [comment]
Also conflicts

**Comment by neb42** [comment]
I can't create a new country
`pq: invalid input syntax for type uuid: "cdh26bdvqc7k2u78d77g"`

**Comment by ludydoo** [comment]
> I can't create a new country `pq: invalid input syntax for type uuid: "cdh26bdvqc7k2u78d77g"`

Should be good now

> Also conflicts 

Yeah that was a pain to rebase

**Comment by ludydoo** [comment]
> COR-505 is a big ticket. Can you add a description outlining what parts of the ticket this covers and what's remaining. This should have been split into sub-tickets and smaller prs probably.

Agreed

**Comment by neb42** [comment]
I've pushed up some styling changes that I did before, but got lost in a rebase or something

**Comment by neb42** [comment]
It looks like the new individual page isn't working. I get a nil pointer expection

**Comment by neb42** [comment]
When creating a new individual you get `failed to create individual form        {"request_id": "afbdcb2d-96a6-427d-81ff-22b002134ace", "user": "https://localhost:10000:EASY_TO_REMEMBER_LOGIN__global", "error": "unknown gender: "}`

But also this block in the handler:
```
individualForm, err = views.NewIndividualForm(individual)
	if err != nil {
		l.Error("failed to create individual form", zap.Error(err))
		err = apierrs.ErrorFrom(err)
		render()
		return
	}
```
When this calls `render` something has a nil pointer. I guess the form because it tries to render the form, but it failed to create the form?

**Comment by ludydoo** [comment]
@neb42 I'm gonna split up the PR into multiple smaller PRs. Gonna make it easier

**Pull request closed without merging**
