### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by neb42**
## What have you implemented?

* Use a logger package to provide better log formats/standards

## Extra/next steps

* Use logger package going forward
* Decide on best practices of what to log

### CODE REVIEW

**Review by dfigueroa87 — APPROVED** [review]
Looks good! 
What were the reasons to choose `pino`? Just curious. I haven't used it before, but read good things about it.

**Comment by neb42** [comment]
> Looks good! What were the reasons to choose `pino`? Just curious. I haven't used it before, but read good things about it.

I did a review and pino and winston were the top two. pino had better defaults and a lot of people are using it because it by far the fastest logger for js.

**Comment by neb42** [comment]
> for some reason this seems to log every single request object, which seems a bit much

My understanding is that logging requests is best practice

**Comment by dfigueroa87** [comment]
Good point @internetti. Maybe it's better to separate the http logger from the app logger? Probably also mute/disable the http logger for `local` env.

And I wonder, how is the logger connected to Azure? As in, how do we see the logs in Azure? (I think it also makes sense to have them separated there)

> I did a review and pino and winston were the top two. pino had better defaults and a lot of people are using it because it by far the fastest logger for js.
Sounds good, I recall you mentioned `Axe` too in the past, did you consider that one as well?

**Comment by neb42** [comment]
> Good point @internetti. Maybe it's better to separate the http logger from the app logger? Probably also mute/disable the http logger for `local` env.
Personally I find it useful to have http logs when developing, but I can look into how this is configured. One option would be for you to set the log level to `warning`. There's also likely a bunch of configuration we want to do, but I thought this is a sensible start.

> And I wonder, how is the logger connected to Azure? As in, how do we see the logs in Azure? (I think it also makes sense to have them separated there)
This is something I want devops to look into. I think this log package ensures that each log is on a single line, making it easier to read in Azure. But really we need to look at having a grafana instance (or similar) set up. Grafana should then read parse the json properly.

> > I did a review and pino and winston were the top two. pino had better defaults and a lot of people are using it because it by far the fastest logger for js.
> 
> Sounds good, I recall you mentioned `Axe` too in the past, did you consider that one as well?
Yeah, I looked at `Cabin.js` which uses `Axe` but there were some issues. One being the developer's aversion to typescript and refusal to support it.

**Comment by neb42** [comment]
Sorry fucked up a rebase here, let me fix it

**Pull request merged**
