### PR TITLE
Core24 302 frontend add sort control

### PR DESCRIPTION
**Pull request by neb42**
Jira ticket: JIRA-CORE24-302

## What have you implemented?

* Add hook to manage sorting
* Add component for sorting controls
* Add sorting to entity list view
* Cleanup some divs on the entity list page

## How to test it?

* Sort the list page, see correct sorting order

### CODE REVIEW

**Review by internetti — COMMENTED** [review]
I guess we can do that later, but I think it might be good to have the sorting parameters in the url, maybe people would like to share/download (later) sorted lists

**Comment by neb42** [comment]
> I guess we can do that later, but I think it might be good to have the sorting parameters in the url, maybe people would like to share/download (later) sorted lists

Related to a comment I'll make in the retro, but lets do it later

**Comment by internetti** [comment]
could you also quickly fix the order of the enums? with 'other' being last?

**Comment by neb42** [comment]
> could you also quickly fix the order of the enums? with 'other' being last?

Won't do this now

> actually, could you fix the footer height, or put the sort by to the left of the dropdowns? the pagination is too far down

It looks fine to me, got a screenshot?

**Comment by internetti** [comment]
> > actually, could you fix the footer height, or put the sort by to the left of the dropdowns? the pagination is too far down
> 
> It looks fine to me, got a screenshot?

having migration issues, making a screenshot would be quite annoying right now, I think it happens when you make the screen smaller, when the scroll bar appears

**Comment by neb42** [comment]
> > > actually, could you fix the footer height, or put the sort by to the left of the dropdowns? the pagination is too far down
> > 
> > 
> > It looks fine to me, got a screenshot?
> 
> having migration issues, making a screenshot would be quite annoying right now, I think it happens when you make the screen smaller, when the scroll bar appears

No I still can't reproduce. I'm going to merge. If you can reproduce it then we can fix it in a new pr.

**Pull request merged**
