### PR TITLE
COR-660: Rename existing sheet rather than creating a new one

### PR DESCRIPTION
**Pull request by neb42**

### CODE REVIEW

**Review by internetti — COMMENTED** [review]
directly reuploading the file I downloaded leads to the error `failed to parse excel file: unknown column: created_at`

**Comment by neb42** [comment]
> directly reuploading the file I downloaded leads to the error `failed to parse excel file: unknown column: created_at`

Check my other pr. This error was hidden by the previous error.

**Comment by internetti** [comment]
yeah, just noticed that. could you rebase one of them on the other, so that testing is easier?

**Review by internetti — APPROVED** [review]

**Comment by internetti** [comment]
lgtm

**Pull request merged**
